### ISSUE TITLE
How do I set barrows items as the target?

### ISSUE THREAD

**Issue by joshi-sh** [Godofdrakes/barrows-potential#4]
I would like to farm for barrows gear, there is not entry for that in the reward target list

**Comment by withoutgettingwet** [comment]
Reward potential doesn't actually affect the drop rate of uniques, so it's best to leave it set to Blood Runes for the highest average rewards. [Reward potential is used in determining what rewards you get _after_ you've failed the roll for a unique.](https://x.com/JagexKieren/status/705428283509366785)

If you want the uniques as fast as possible you can actually ignore reward potential, but you will get worse rewards when you _don't_ get a unique and you won't save much time either.

<details>
  <summary>Explanation of why Blood Runes are recommended</summary>
The items that are added into the drop table at >881 reward potential and above are actually worth _less_ than the runes, or in the are so rare that their higher value is not enough to offset the lower value bolt racks you will getting in place of what would have otherwise been runes. 
</details>

**Comment by joshi-sh** [comment]
Gotcha, thanks!
